### ISSUE TITLE
General instability and console bugs

### ISSUE THREAD

**Issue by danielvianna** [agoldis/sorry-cypress#72]
My Digital Ocean was on and off and I could not figure out whether it was a problem on the server side or database. 

I suddenly lost all of the data, then it came back out of the blue. Then I lost again (it said no data on the dashboard) then a CORS problem on Chrome console. For some reason it disappeared after I whitelisted http://cypressdashboard.id.cast-soft.com:4000 (graphQL schema) in Bitdefender Antivirus (not my choice company policy). However, I don't know if that was related because the reason I had to whitelist was that it was being displayed as a possible phishing website.

Can you please record a quick video on how to run on debug mode the 3 instances on a baremetal or digital ocean server? I'm a beginner in programming but I was able to solve some basic security issues on a simple node app (without docker) by installing and configuring Helmet, then running against security scanners such as Mozilla Observatory.

Also is there a way to avoid having to access the dashboard without the 8080 on the URL or using a redirect?

I'm getting these errors on console (please check http://cypressdashboard.id.cast-soft.com:8000)

```
react-dom.development.js:88 Warning: Encountered two children with the same key, `972f7bb96abf8f878b49ffb0ddff5f63`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in RunsView (created by Context.Consumer)
    in Route (created by Root)
    in section (created by Content)
    in Content (created by Root)
    in ErrorBoundary (created by Root)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Root)
    in ThemeProvider (created by Root)
    in ApolloProvider (created by Root)
    in Root
printWarning @ react-dom.development.js:88
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/@apollo/react-common/lib/react-common.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/ts-invariant/lib/invariant.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/apollo-client/bundle.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/apollo-utilities/lib/bundle.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/@wry/equality/lib/equality.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/apollo-link/lib/bundle.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/zen-observable-ts/lib/bundle.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router-dom/esm/react-router-dom.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router/esm/react-router.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by danielvianna** [comment]
**This is my docker-compose.full**

```
version: "3.6"

services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017

  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://198.199.86.198:8080
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_DATABASE: "sorry-cypress"
      EXECUTION_DRIVER: "../execution/mongo/driver"
      SCREENSHOTS_DRIVER: "../screenshots/s3.driver"
      AWS_ACCESS_KEY_ID: "keyomittedonpurpose"
      AWS_SECRET_ACCESS_KEY: "keyomittedonpurpose"
      S3_BUCKET: "sorrycypressbucket"
      S3_REGION: "ca-central-1"
    ports:
      - 1234:1234
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      MONGODB_DATABASE: "sorry-cypress"
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://198.199.86.198:4000
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api

```


**This is my docker-compose.yml**

```
version: '3.6'

services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017

  api:
    build:
      context: $PWD/packages/api
      dockerfile: Dockerfile.dev
    ports:
      - 9230:9230
      - 4000:4000
    volumes:
      - $PWD/packages/api/src:/app/src
    depends_on:
      - mongo

  director:
    build:
      context: $PWD/packages/director
      dockerfile: Dockerfile.dev
    environment:
      DASHBOARD_URL: http://198.199.86.198:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/s3.driver'
      S3_BUCKET: sorry-cypress
    ports:
      - 9229:9229
      - 1234:1234
    volumes:
      - $PWD/packages/director/src:/app/src
      - $PWD/packages/director/config:/app/config
    depends_on:
      - mongo
```
