### ISSUE TITLE
AWS Codebuild run does not connect to Heroku Director URL

### ISSUE THREAD

**Issue by jeansymolanza** [agoldis/sorry-cypress#77]
I have set up an AWS Codebuild build.yaml as follows as per https://github.com/agoldis/sorry-cypress/issues/6#issuecomment-598695346:

```
version: 0.2

phases:
  pre_build:
    commands:
      - curl -L ${CYPRESS_DIRECTOR_URL}/ping
      - apt-get update -y
      - apt-get install -y dbus-x11 apt-transport-https libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb libgtk-3-0 libnss3 libxss1 libasound2 libxtst6 xauth
      - cd $CODEBUILD_SRC_DIR
      - npm ci
      - npm install concurrently wait-on -g
      - export TERM=xterm
      - export DBUS_SESSION_BUS_ADDRESS=/dev/null
      - sed -i -E "s@(api_url:) (.*)@\1 \"${CYPRESS_DIRECTOR_URL}/\"@g" /root/.cache/Cypress/*/Cypress/resources/app/packages/server/config/app.yml
  build:
    commands:
      - npm run test-headless
      - npm run cy:verify
      - npm run serve &
      - Xvfb :99 &
      - export DISPLAY=:99 &
      - unset NODE_OPTIONS
      - CYPRESS_CI_RUN_COMMAND="npm run cy:run -- --record --key ci-tests --parallel --ci-build-id Runner-${CODEBUILD_START_TIME}-${CODEBUILD_BUILD_ID}"
      - |
      - wait-on http://localhost:4200 && concurrently \
        "$CYPRESS_CI_RUN_COMMAND" \
        "$CYPRESS_CI_RUN_COMMAND"
      - pkill Xvfb

artifacts:
  files:
    - '**/*'
  base-directory: './cypress/results'
```

CYPRESS_DIRECTOR_URL is my Heroku Director URL (https://opsonion-ci.herokuapp.com). I could not figure out how to set up the Cloudformation stack due to incessant errors, so resorted to this approach.

Strangely enough, my test runs are not being picked up by the Heroku Director URL. The same set of tests run twice. I have tested the setup locally by running the following cmd script:

```
start cypress run --record --key ci-tests --parallel --ci-build-id Runner
```

The connections are picked up fine from my local machine.

My question: is it not possible to have a AWS Codebuild and Heroku (free) configuration setup? It might be ideal for people who don't want the overhead of paying for a long-running director/dashboard/api instance, especially as CodeBuild is pay per use.
